wiki/plugins/attachments/urls.py
from django.conf.urls import patterns, url

from wiki.plugins.attachments import views

urlpatterns = patterns('',
    url(r'^$', views.AttachmentView.as_view(), name='attachments_index'),
    url(r'^search/$', views.AttachmentSearchView.as_view(), name='attachments_search'),
    url(r'^add/(?P<attachment_id>\d+)/$', views.AttachmentAddView.as_view(), name='attachments_add'),
    url(r'^replace/(?P<attachment_id>\d+)/$', views.AttachmentReplaceView.as_view(), name='attachments_replace'),
    url(r'^history/(?P<attachment_id>\d+)/$', views.AttachmentHistoryView.as_view(), name='attachments_history'),
    url(r'^download/(?P<attachment_id>\d+)/$', views.AttachmentDownloadView.as_view(), name='attachments_download'),
    url(r'^delete/(?P<attachment_id>\d+)/$', views.AttachmentDeleteView.as_view(), name='attachments_delete'),
    url(r'^download/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$', views.AttachmentDownloadView.as_view(), name='attachments_download'),
    url(r'^change/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$', views.AttachmentChangeRevisionView.as_view(), name='attachments_revision_change'),
)

wiki/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include

from wiki.conf import settings
from wiki.core.plugins import registry
from wiki.views import article, accounts
from wiki.core.utils import get_class_from_str


class WikiURLPatterns(object):
    '''
    configurator for wiki urls.

    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    custom_root_view_class = get_class_from_str(settings.CUSTOM_ROOT_VIEW) if settings.CUSTOM_ROOT_VIEW else None
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view = article.ChangeRevisionView
    revision_merge_view = 'wiki.views.article.merge'

    search_view_class = settings.SEARCH_VIEW
    article_diff_view = 'wiki.views.article.diff'

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()

        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = patterns('',
            url('^$', self.custom_root_view_class.as_view() if self.custom_root_view_class else self.article_view_class.as_view(), name='root', kwargs={'path': ''}),
            url('^create-root/$', article.CreateRootView.as_view(), name='root_create'),
            url('^_search/$', get_class_from_str(self.search_view_class).as_view(), name='search'),
            url('^_revision/diff/(?P<revision_id>\d+)/$', self.article_diff_view, name='diff'),
       )
        return urlpatterns

    def get_accounts_urls(self):
        urlpatterns = patterns('',
            url('^_accounts/sign-up/$', self.signup_view_class.as_view(), name='signup'),
            url('^_accounts/logout/$', self.logout_view_class.as_view(), name='logout'),
            url('^_accounts/login/$', self.login_view_class.as_view(), name='login'),
           )
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = patterns('',
            # This one doesn't work because it don't know where to redirect after...
            url('^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$', self.revision_change_view.as_view(), name='change_revision'),
            url('^_revision/preview/(?P<article_id>\d+)/$', self.article_preview_view_class.as_view(), name='preview_revision'),
            url('^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$', self.revision_merge_view, name='merge_revision_preview', kwargs={'preview': True}),
           )
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = patterns('',
            # Paths decided by article_ids
            url('^(?P<article_id>\d+)/$', self.article_view_class.as_view(), name='get'),
            url('^(?P<article_id>\d+)/delete/$', self.article_delete_view_class.as_view(), name='delete'),
            url('^(?P<article_id>\d+)/deleted/$', self.article_deleted_view_class.as_view(), name='deleted'),
            url('^(?P<article_id>\d+)/edit/$', self.article_edit_view_class.as_view(), name='edit'),
            url('^(?P<article_id>\d+)/preview/$', self.article_preview_view_class.as_view(), name='preview'),
            url('^(?P<article_id>\d+)/history/$', self.article_history_view_class.as_view(), name='history'),
            url('^(?P<article_id>\d+)/settings/$', self.article_settings_view_class.as_view(), name='settings'),
            url('^(?P<article_id>\d+)/source/$', self.article_source_view_class.as_view(), name='source'),
            url('^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$', self.revision_change_view.as_view(), name='change_revision'),
            url('^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$', self.revision_merge_view, name='merge_revision'),
            url('^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$', self.article_plugin_view_class.as_view(), name='plugin'),
           )
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = patterns('',
            # Paths decided by URLs
            url('^(?P<path>.+/|)_create/$', self.article_create_view_class.as_view(), name='create'),
            url('^(?P<path>.+/|)_delete/$', self.article_delete_view_class.as_view(), name='delete'),
            url('^(?P<path>.+/|)_deleted/$', self.article_deleted_view_class.as_view(), name='deleted'),
            url('^(?P<path>.+/|)_edit/$', self.article_edit_view_class.as_view(), name='edit'),
            url('^(?P<path>.+/|)_preview/$', self.article_preview_view_class.as_view(), name='preview'),
            url('^(?P<path>.+/|)_history/$', self.article_history_view_class.as_view(), name='history'),
            url('^(?P<path>.+/|)_dir/$', self.article_dir_view_class.as_view(), name='dir'),
            url('^(?P<path>.+/|)_settings/$', self.article_settings_view_class.as_view(), name='settings'),
            url('^(?P<path>.+/|)_source/$', self.article_source_view_class.as_view(), name='source'),
            url('^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$', self.revision_change_view.as_view(), name='change_revision'),
            url('^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$', self.revision_merge_view, name='merge_revision'),
            url('^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$', self.article_plugin_view_class.as_view(), name='plugin'),
            # This should always go last!
            url('^(?P<path>.+/|)$', self.article_view_class.as_view(), name='get'),
           )
        return urlpatterns

    def get_plugin_urls(self):
        urlpatterns = patterns('',)
        for plugin in registry.get_plugins().values():
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += patterns('',
                    url('^(?P<article_id>\d+)/plugin/' + slug + '/', include(article_urlpatterns)),
                    url('^(?P<path>.+/|)_plugin/' + slug + '/', include(article_urlpatterns)),
                )
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += patterns('',
                    url('^_plugin/' + slug + '/', include(root_urlpatterns)),
               )
        return urlpatterns

def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if url_config_class is None:
        url_config_classname=getattr(settings, 'URL_CONFIG_CLASS', None)
        if url_config_classname is None:
            url_config_class = WikiURLPatterns
        else:
            url_config_class = get_class_from_str(url_config_classname)
    urlpatterns = url_config_class().get_urls()
    return urlpatterns, app_name, namespace


######################
# PLUGINS
######################

from wiki.core.plugins.loader import load_wiki_plugins

load_wiki_plugins()

wiki/templates/wiki/article.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags %}
{% load url from future %}

{% block wiki_pagetitle %}{{ article.current_revision.title }}{% endblock %}

{% block wiki_breadcrumbs %}
{% include "wiki/includes/breadcrumbs.html" %}
{% endblock %}

{% block wiki_contents %}

    {% addtoblock "js" %}
        <script type="text/javascript" src="{{ STATIC_URL }}wiki/js/bootstrap-lightbox.js"></script>
    {% endaddtoblock %}

        <div id="article-container">
            <ul class="nav nav-pills" id="article-menu">
              <li class="pull-left" id="article-title-li">

                  <small style="font-size: 14px;">
                    {% if urlpath.parent %}
                    <a href="{% url 'wiki:get' path=urlpath.path %}"><span class="icon-bookmark"></span> {{ article.current_revision.title }}</a>
                    {% endif %}
                    {% if article.current_revision.locked %}
                      <span class="icon-lock"></span> {% trans "locked" %}
                    {% endif %}
                  </small>

              </li>
              {% include "wiki/includes/article_menu.html" %}
            </ul>
            <h1 id="article-title">{{ article.current_revision.title }}</h1>
            <div>
              {% block wiki_contents_tab %}
              {% endblock %}
            </div>
        </div>
{% endblock %}

{% block wiki_footer_prepend %}
  <p style="margin-bottom: 10px;"><em>{% trans "This article was last modified:" %} {{ article.current_revision.modified }}</em></p>
{% endblock %}

wiki/templates/wiki/base.html
{% load sekizai_tags i18n wiki_tags static %}{% load url from future %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block wiki_pagetitle %}{% endblock %}{% block wiki_pagetitle_suffix %} - django-\/\/  i K |{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="www.django-wiki.org">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}wiki/bootstrap/css/wiki-bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}wiki/css/pygments.css" rel="stylesheet">
    {% block extra_css %}{% endblock %}
    {% render_block "css" %}
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    {% block wiki_body %}
    
    {% block wiki_navbar %}

    <div class="navbar navbar-fixed-top navbar-default">
      <div class="navbar-inverse" style="height:20px;">
          <div class="container">
          </div>
      </div>
      <div class="container">
        <!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        {% block wiki_header_branding %}
        <a class="navbar-brand" href="{% url 'wiki:root' %}">django-\/\/ i K |</a>
        {% endblock %}
        <div class="">

          <div class="pull-right-block-on-responsive">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="badge notification-cnt">0</span>
                  {{ user }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" style="left:auto; right:0; left: auto; max-height: 400px; overflow: scroll;">
                  <li>
                    <a href="{% url 'wiki:logout' %}">
                      <i class="icon-off"></i>
                      {% trans "Log out" %}
                    </a>
                  </li>
                  {% include "wiki/plugins/notifications/menubaritem.html" %}
                </ul>
              </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
              <li>
                <a href="{% login_url as wiki_login_url %}{{ wiki_login_url }}"><i class="icon-signin"></i> {% trans "Log in" %}</a>
              </li>
              <li>
                <a href="{% url 'wiki:signup' %}"><i class="icon-plus"></i> {% trans "Sign up" %}</a>
              </li>
            </ul>
            {% endif %}
          </div>
          <form class="navbar-form pull-right-block-on-responsive" id="wiki-search-form" method="GET" action="{% url 'wiki:search' %}">
            <div class="input-group">
              <input type="search" class="form-control search-query" name="q" placeholder="{% trans "Search..." %}" />
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                  <span class="icon-search"></span>
                </button>
              </span>
            </div><!-- /input-group -->
          </form>
          {% block wiki_header_navbar %}
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">{% trans "Home" %}</a></li>
            <li><a href="https://github.com/benjaoming/django-wiki" target="_blank">{% trans "About" %}</a></li>
          </ul>
          {% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}
    <div class="horizontal-navigation">
    <div class="container">
    <!-- Reserved for breadcrumbs -->
      {% block wiki_breadcrumbs %}{% endblock %}

    </div>


    </div>
    <div class="container container-alert">
     {% if messages %}
        <!-- Messages for this instance -->
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} fade in">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <div class="container no-padding-container">
      <!-- Main page contents go here -->
      {% block wiki_contents %}{% endblock %}
    </div>
    <div class="container">
      <footer id="wiki-footer">
        {% block wiki_footer %}
            <hr />
            {% block wiki_footer_logo %}
            {% endblock %}
            {% block wiki_footer_prepend %}
            {% endblock %}
            <p>{% blocktrans %}Powered by <a href="http://www.django-wiki.org">django-wiki</a>, an open source application under the <a href="http://www.gnu.org/licenses/quick-guide-gplv3.html">GPLv3</a> license. Let knowledge be the cure.{% endblocktrans %}</p>
            <div style="clear: both"></div>
        {% endblock %}
      </footer>

    </div> <!-- /container -->

    {% endblock %}

    <script src="{{ STATIC_URL }}wiki/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}wiki/js/core.js"></script>
    <script src="{{ STATIC_URL }}wiki/bootstrap/js/bootstrap.min.js"></script>
    <!-- Optionally enable responsive features in IE8 -->
    <script src="{{ STATIC_URL }}wiki/js/respond.min.js"></script>
    {% render_block "js" %}
  
  </body>
</html>

wiki/templates/wiki/edit.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n %}
{% load url from future %}

{% block wiki_pagetitle %}{% trans "Edit" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% if not user.is_authenticated %}
<p class="alert alert-warning">
{% trans "<strong>Warning:</strong> You are not logged in. Your IP address will be logged." %}
<a href="{% url 'wiki:login' %}?next={% url 'wiki:edit' article_id=article.id path=urlpath.path %}">{% trans "Click here to log in" %} &raquo;</a>
</p>
{% endif %}

<div class="row">

  <div class="col-lg-8">
    <form method="POST" class="form-horizontal" id="article_edit_form">
      <input type="hidden" name="save" value="1" />
      <input type="hidden" name="preview" value="1" />
      {% with edit_form as form %}
        {% include "wiki/includes/editor.html" %}
      {% endwith %}
    </form>
  </div>

  <div class="col-lg-4" id="wiki-edit-sidebar">
    {% include "wiki/includes/editor_sidebar.html" %}
  </div>

</div>

<div style="clear: both"></div>

<div class="form-group form-actions">
  <div class="col-lg-8">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <a class="btn btn-default btn-large" onclick="$('#previewModal').modal('show'); document.getElementById('article_edit_form').target='previewWindow'; document.getElementById('article_edit_form').action='{% url 'wiki:preview' path=urlpath.path article_id=article.id %}'; $('#article_edit_form').submit()" href="#">
        <span class="icon-eye-open"></span>
        {% trans "Preview" %}
      </a>
      <a class="btn btn-large btn-primary" onclick="document.getElementById('article_edit_form').target=''; document.getElementById('article_edit_form').action='{% url 'wiki:edit' path=urlpath.path article_id=article.id %}'; $('#article_edit_form').submit();" href="#">
        <span class="icon-ok"></span>
        {% trans "Save changes" %}
      </a>
    </div>
  </div>
  {% if article|can_delete:user %}
  <div class="col-lg-4">
    <div class="pull-right">
    <a href="{% url 'wiki:delete' path=urlpath.path article_id=article.id %}" class="btn btn-danger">
      <span class="icon-trash"></span>
      {% trans "Delete article" %}
    </a>
    </div>
  </div>
  {% endif %}
</div>

{% include "wiki/includes/modals.html" %}

<div class="modal fade wiki-modal" id="previewModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <iframe name="previewWindow" frameborder="0"></iframe>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default btn-large" data-dismiss="modal">
          <span class="icon-circle-arrow-left"></span>
          {% trans "Back to editor" %}
        </a>
        <a class="btn btn-large btn-primary" onclick="document.getElementById('article_edit_form').target=''; document.getElementById('article_edit_form').action='{% url 'wiki:edit' path=urlpath.path article_id=article.id %}'; document.getElementById('article_edit_form').submit();" href="#">
          <span class="icon-ok"></span>
          {% trans "Save changes" %}
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

wiki/templates/wiki/history.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags %}
{% load url from future %}

{% block wiki_pagetitle %}{% trans "History" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% include "wiki/includes/modals.html" %}

{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/diffview.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/diff.js"></script>
{% endaddtoblock %}
{% addtoblock "css" %}
<style type="text/css">
  td.linenumber {
    width: 20px;
  }
  tr.insert td {
    background-color: #DFC;
  }
  tr.delete td {
    background-color: #FDC;
  }
  tr.equal td {
    background-color: #F2F2F2;
  }
  
  .diff-container td {
    white-space: pre; font-family: monospace;
  }
  .diff-container td,
  .diff-container th {
    padding: 2px 7px;
    border-right: 1px solid #DDD;    
  }
  .diff-container td:last-child,
  .diff-container th:last-child {
    border-right: none;
  }
  .diff-container table {
    border-top: 1px solid #DDD;    
  }
</style>
{% endaddtoblock %}

<p class="lead">
  {% trans "Click each revision to see a list of edited lines. Click the Preview button to see how the article looked at this stage. At the bottom of this page, you can change to a particular revision or merge an old revision with the current one." %}
</p>

<form method="GET">
  <div class="tab-content" style="overflow: visible;">
    {% for revision in revisions %}
      <div class="accordion" id="accordion{{ revision.revision_number }}">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" style="float: left;" href="#collapse{{ revision.revision_number }}" onclick="get_diff_json('{% url 'wiki:diff' revision.id %}', $('#collapse{{ revision.revision_number }}'))">
              {% if revision == article.current_revision %}
                <i class="icon-flag"></i>
              {% else %}
                <i class="icon-plus"></i>
              {% endif %}
              {% include "wiki/includes/revision_info.html" with current_revision=article.current_revision %}
              <div style="color: #CCC;">
                <small>
                {% if revision.user_message %}
                  {{ revision.user_message }}
                {% elif revision.automatic_log %}
                  {{ revision.automatic_log }}
                {% else %}
                  ({% trans "no log message" %})
                {% endif %}
                </small>
              </div>
            </a>
            <div class="progress progress-striped active" style="display: none; width: 40px; float: left; margin-top: 7px; margin-bottom: -7px;">
              <div class="bar" style="width: 100%;"></div>
            </div>
            <div class="pull-right" style="vertical-align: middle; margin: 8px 8px;">
              {% if revision == article.current_revision %}
              <a href="#" class="btn btn-default disabled">
                <span class="icon-lock"></span>
                {% trans "Preview this revision" %}
              </a>
              {% else %}
              <button type="submit" class="btn btn-default" onclick="$('#previewModal').modal('show'); this.form.target='previewWindow'; this.form.r.value='{{ revision.id }}'; this.form.action='{% url 'wiki:preview_revision' article.id %}'; $('#previewModal .switch-to-revision').attr('href', '{% url 'wiki:change_revision' path=urlpath.path article_id=article.id revision_id=revision.id %}')">
                <span class="icon-eye-open"></span>
                {% trans "Preview this revision" %}
              </button>
              {% endif %}
              
              {% if article|can_write:user and not article.current_revision.locked %}
              <input type="radio"{% if revision == article.current_revision %} disabled="true"{% endif %} style="margin: 0 10px;" value="{{ revision.id }}" name="revision_id" switch-button-href="{% url 'wiki:change_revision' path=urlpath.path revision_id=revision.id %}" merge-button-href="{% url 'wiki:merge_revision_preview' article_id=article.id revision_id=revision.id %}" merge-button-commit-href="{% url 'wiki:merge_revision' path=urlpath.path article_id=article.id revision_id=revision.id %}" />
              {% endif %}
              
            </div>
            <div style="clear: both"></div>
          </div>
          <div id="collapse{{ revision.revision_number }}" class="accordion-body collapse">
            <div class="accordion-inner diff-container" style="padding: 0;">
              <dl class="dl-horizontal">
                <dt>{% trans "Auto log:" %}</dt>
                <dd>{{ revision.automatic_log|default:"-"|linebreaksbr }}</dd>
              </dl>
              <table class="table table-condensed" style="margin: 0; border-collapse: collapse;">
                <thead>
                  <tr>
                    <th class="linenumber">{% if revision.previous_revision %}#{{revision.previous_revision.revision_number}}{% endif %}</th>
                    <th class="linenumber">#{{revision.revision_number}}</th>
                    <th>{% trans "Change" %}</th>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    
    {% include "wiki/includes/pagination.html" %}
    
    {% if revisions.count > 1 and article|can_write:user and not article.current_revision.locked %}

    <div class="form-group form-actions">
      <div class="pull-right">
        <button type="submit" name="preview" value="1" class="btn btn-default btn-large" onclick="$('#mergeModal').modal('show'); this.form.target='mergeWindow'; this.form.action=$('input[type=radio]:checked').attr('merge-button-href'); $('.merge-revision-commit').attr('href', $('input[type=radio]:checked').attr('merge-button-commit-href'))">
          <span class="icon-random"></span>
          {% trans "Merge selected with current..." %}
        </button>
        <button type="submit" name="save" value="1" class="btn btn-large btn-primary" onclick="this.form.target='_self'; this.form.action=$('input[type=radio]:checked').attr('switch-button-href')">
          <span class="icon-flag"></span>
          {% trans "Switch to selected version" %}
        </button>
      </div>
      <div style="clear:both"></div>
    </div>
    
    {% endif %}
    
  </div>
  <input type="hidden" name="r" value="" />
  <div class="modal fade wiki-modal" id="previewModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <iframe name="previewWindow" frameborder="0"></iframe>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default btn-large" data-dismiss="modal">
            <span class="icon-circle-arrow-left"></span>
            {% trans "Back to history view" %}
          </a>
          {% if article|can_write:user %}
          <a href="#" class="btn btn-large btn-primary switch-to-revision">
            <span class="icon-flag"></span>
            {% trans "Switch to this version" %}
          </a>
          {% else %}
            <a href="#" class="btn btn-large btn-primary disabled">
              <span class="icon-lock"></span>
              {% trans "Switch to this version" %}
            </a>                    
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade wiki-modal" id="mergeModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1>{% trans "Merge with current" %}</h1>
          <p class="lead"><span class="icon-info-sign"></span> {% trans "When you merge a revision with the current, all data will be retained from both versions and merged at its approximate location from each revision." %} <strong>{% trans "After this, it's important to do a manual review." %}</strong></p>
        </div>
        <div class="modal-body">
          <iframe name="mergeWindow" frameborder="0" style="min-height: 0;"></iframe>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default btn-large" data-dismiss="modal">
            <span class="icon-circle-arrow-left"></span>
            {% trans "Back to history view" %}
          </a>
          {% if article|can_write:user %}
          <a href="#" class="btn btn-large btn-primary merge-revision-commit">
            <span class="icon-file"></span>
            {% trans "Create new merged version" %}
          </a>                    
          {% else %}
            <a href="#" class="btn btn-large btn-primary disabled">
              <span class="icon-lock"></span>
              {% trans "Create new merged version" %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</form>
  
{% endblock %}

wiki/templates/wiki/source.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}
{% load url from future %}

{% block wiki_pagetitle %}{% trans "Source of" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% if article.current_revision.locked %}
<p class="lead">{% trans "This article is currently locked for editing." %}</p>
{% endif %}

<pre class="pre-scrollable">
  {{ article.current_revision.content }}
</pre>

{% endblock %}