wiki/plugins/attachments/urls.py
from django.conf.urls import patterns, url

from wiki.plugins.attachments import views

urlpatterns = patterns('',
    url(r'^$', views.AttachmentView.as_view(), name='attachments_index'),
    url(r'^search/$', views.AttachmentSearchView.as_view(), name='attachments_search'),
    url(r'^add/(?P<attachment_id>\d+)/$', views.AttachmentAddView.as_view(), name='attachments_add'),
    url(r'^replace/(?P<attachment_id>\d+)/$', views.AttachmentReplaceView.as_view(), name='attachments_replace'),
    url(r'^history/(?P<attachment_id>\d+)/$', views.AttachmentHistoryView.as_view(), name='attachments_history'),
    url(r'^download/(?P<attachment_id>\d+)/$', views.AttachmentDownloadView.as_view(), name='attachments_download'),
    url(r'^delete/(?P<attachment_id>\d+)/$', views.AttachmentDeleteView.as_view(), name='attachments_delete'),
    url(r'^download/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$', views.AttachmentDownloadView.as_view(), name='attachments_download'),
    url(r'^change/(?P<attachment_id>\d+)/revision/(?P<revision_id>\d+)/$', views.AttachmentChangeRevisionView.as_view(), name='attachments_revision_change'),
)

wiki/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include

from wiki.conf import settings
from wiki.core.plugins import registry
from wiki.views import article, accounts
from wiki.core.utils import get_class_from_str


class WikiURLPatterns(object):
    '''
    configurator for wiki urls.

    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    custom_root_view_class = get_class_from_str(settings.CUSTOM_ROOT_VIEW) if settings.CUSTOM_ROOT_VIEW else None
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view = article.ChangeRevisionView
    revision_merge_view = 'wiki.views.article.merge'

    search_view_class = settings.SEARCH_VIEW
    article_diff_view = 'wiki.views.article.diff'

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()

        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = patterns('',
            url('^$', self.custom_root_view_class.as_view() if self.custom_root_view_class else self.article_view_class.as_view(), name='root', kwargs={'path': ''}),
            url('^create-root/$', article.CreateRootView.as_view(), name='root_create'),
            url('^_search/$', get_class_from_str(self.search_view_class).as_view(), name='search'),
            url('^_revision/diff/(?P<revision_id>\d+)/$', self.article_diff_view, name='diff'),
       )
        return urlpatterns

    def get_accounts_urls(self):
        urlpatterns = patterns('',
            url('^_accounts/sign-up/$', self.signup_view_class.as_view(), name='signup'),
            url('^_accounts/logout/$', self.logout_view_class.as_view(), name='logout'),
            url('^_accounts/login/$', self.login_view_class.as_view(), name='login'),
           )
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = patterns('',
            # This one doesn't work because it don't know where to redirect after...
            url('^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$', self.revision_change_view.as_view(), name='change_revision'),
            url('^_revision/preview/(?P<article_id>\d+)/$', self.article_preview_view_class.as_view(), name='preview_revision'),
            url('^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$', self.revision_merge_view, name='merge_revision_preview', kwargs={'preview': True}),
           )
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = patterns('',
            # Paths decided by article_ids
            url('^(?P<article_id>\d+)/$', self.article_view_class.as_view(), name='get'),
            url('^(?P<article_id>\d+)/delete/$', self.article_delete_view_class.as_view(), name='delete'),
            url('^(?P<article_id>\d+)/deleted/$', self.article_deleted_view_class.as_view(), name='deleted'),
            url('^(?P<article_id>\d+)/edit/$', self.article_edit_view_class.as_view(), name='edit'),
            url('^(?P<article_id>\d+)/preview/$', self.article_preview_view_class.as_view(), name='preview'),
            url('^(?P<article_id>\d+)/history/$', self.article_history_view_class.as_view(), name='history'),
            url('^(?P<article_id>\d+)/settings/$', self.article_settings_view_class.as_view(), name='settings'),
            url('^(?P<article_id>\d+)/source/$', self.article_source_view_class.as_view(), name='source'),
            url('^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$', self.revision_change_view.as_view(), name='change_revision'),
            url('^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$', self.revision_merge_view, name='merge_revision'),
            url('^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$', self.article_plugin_view_class.as_view(), name='plugin'),
           )
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = patterns('',
            # Paths decided by URLs
            url('^(?P<path>.+/|)_create/$', self.article_create_view_class.as_view(), name='create'),
            url('^(?P<path>.+/|)_delete/$', self.article_delete_view_class.as_view(), name='delete'),
            url('^(?P<path>.+/|)_deleted/$', self.article_deleted_view_class.as_view(), name='deleted'),
            url('^(?P<path>.+/|)_edit/$', self.article_edit_view_class.as_view(), name='edit'),
            url('^(?P<path>.+/|)_preview/$', self.article_preview_view_class.as_view(), name='preview'),
            url('^(?P<path>.+/|)_history/$', self.article_history_view_class.as_view(), name='history'),
            url('^(?P<path>.+/|)_dir/$', self.article_dir_view_class.as_view(), name='dir'),
            url('^(?P<path>.+/|)_settings/$', self.article_settings_view_class.as_view(), name='settings'),
            url('^(?P<path>.+/|)_source/$', self.article_source_view_class.as_view(), name='source'),
            url('^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$', self.revision_change_view.as_view(), name='change_revision'),
            url('^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$', self.revision_merge_view, name='merge_revision'),
            url('^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$', self.article_plugin_view_class.as_view(), name='plugin'),
            # This should always go last!
            url('^(?P<path>.+/|)$', self.article_view_class.as_view(), name='get'),
           )
        return urlpatterns

    def get_plugin_urls(self):
        urlpatterns = patterns('',)
        for plugin in registry.get_plugins().values():
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += patterns('',
                    url('^(?P<article_id>\d+)/plugin/' + slug + '/', include(article_urlpatterns)),
                    url('^(?P<path>.+/|)_plugin/' + slug + '/', include(article_urlpatterns)),
                )
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += patterns('',
                    url('^_plugin/' + slug + '/', include(root_urlpatterns)),
               )
        return urlpatterns

def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if url_config_class is None:
        url_config_classname=getattr(settings, 'URL_CONFIG_CLASS', None)
        if url_config_classname is None:
            url_config_class = WikiURLPatterns
        else:
            url_config_class = get_class_from_str(url_config_classname)
    urlpatterns = url_config_class().get_urls()
    return urlpatterns, app_name, namespace


######################
# PLUGINS
######################

from wiki.core.plugins.loader import load_wiki_plugins

load_wiki_plugins()

wiki/templates/wiki/includes/anonymous_blocked.html
{% load i18n %}
{% load url from future %}
<em>
{% url 'wiki:signup' as signup_url %}
{% url 'wiki:login' as login_url %}
{% if login_url and signup_url %}
  {% blocktrans %}
  You need to <a href="{{ login_url }}">log in</a> or <a href="{{ signup_url }}">sign up</a> to use this function.
  {% endblocktrans %}
{% else %}
  {% trans "You need to log in or sign up to use this function." %}
{% endif %}
</em>

wiki/templates/wiki/includes/article_menu.html
{% load i18n wiki_tags %}{% load url from future %}

{% with selected_tab as selected %}

<li class="pull-right{% if selected == "settings" %} active{% endif %}">
  {% if not user.is_anonymous %}
  <a href="{% url 'wiki:settings' article_id=article.id path=urlpath.path %}">
    <span class="icon-wrench"></span>
    {% trans "Settings" %}
  </a>
  {% endif %}
</li>

{% for plugin in article_tabs %}
  <li class="pull-right{% if selected == plugin.slug %} active{% endif %}">
    <a href="{% url 'wiki:plugin' slug=plugin.slug article_id=article.id path=urlpath.path %}">
      <span class="{{ plugin.article_tab.1 }}"></span>
      {{ plugin.article_tab.0 }}
    </a>
  </li>
{% endfor %}

<li class="pull-right{% if selected == "history" %} active{% endif %}">
  <a href="{% url 'wiki:history' article_id=article.id path=urlpath.path %}">
    <span class="icon-time"></span>
    {% trans "Changes" %}
  </a>
</li>

{% if article|can_write:user and not article.current_revision.locked %}
<li class="pull-right{% if selected == "edit" %} active{% endif %}">
  <a href="{% url 'wiki:edit' article_id=article.id path=urlpath.path %}">
    <span class="icon-edit"></span>
    {% trans "Edit" %}
  </a>
</li>
{% else %}
<li class="pull-right{% if selected == "source" %} active{% endif %}">
  <a href="{% url 'wiki:source' article_id=article.id path=urlpath.path %}">
    <span class="icon-lock"></span>
    {% trans "View Source" %}
  </a>
</li>
{% endif %}

<li class="pull-right{% if selected == "view" %} active{% endif %}">
  <a href="{% url 'wiki:get' article_id=article.id path=urlpath.path %}">
    <span class="icon-home"></span>
    {% trans "View" %}
  </a>
</li>

{% endwith %}

wiki/templates/wiki/includes/breadcrumbs.html
{% load i18n %}{% load url from future %}
{% if urlpath %}
<div id="article-breadcrumbs">

<ul class="breadcrumb pull-left">
  {% for ancestor in urlpath.cached_ancestors %}
    <li><a href="{% url 'wiki:get' path=ancestor.path %}">{{ ancestor.article.current_revision.title}}</a></li>
    <li><i class="icon icon-chevron-right"></i></li>

  {% endfor %}
  <li class="active">{{ article.current_revision.title }}</li>
</ul>
<div class="pull-right">
  <div class="btn-group">
    <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 7px;" title="{% trans "Sub-articles for" %} {{ article.current_revision.title }}">
      <span class="icon-sitemap"></span>
    </a>
    <ul class="dropdown-menu horizontal-dropdown-menu">
      {% for child in children_slice %}
        <li>
          <a href="{% url 'wiki:get' path=child.path %}">
            {{ child.article.current_revision.title }}
          </a>
        </li>
        {% empty %}
        <li><a href="#"><em>{% trans "No sub-articles" %}</em></a></li>
      {% endfor %}
      {% if children_slice_more %}
      <li><a href="#"><em>{% trans "...and more" %}</em></a></li>
      {% endif %}
      <li class="divider"></li>
      <li>
        <a href="{% url 'wiki:dir' path=urlpath.path %}">{% trans "Browse articles in this level" %} &raquo;</a>
      </li>
    </ul>
  </div>
</div>
<div class="pull-right">
  <div class="btn-group">
    <a class="btn btn-green btn-info dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 7px;" title="{% trans "Sub-articles for" %} {{ article.current_revision.title }}">
      <span class="icon-plus"></span>
    </a>    
    <ul class="dropdown-menu horizontal-dropdown-menu">
      <li>
        {% if urlpath.parent %}
        <a href="{% url 'wiki:create' path=urlpath.parent.path %}">
          <span class="icon-arrow-right"></span>
          {% trans "New article next to" %} {{ article.current_revision.title }}
        </a>
        {% endif %}
        <a href="{% url 'wiki:create' path=urlpath.path %}">
          <span class="icon-arrow-down"></span>
          {% trans "New article below" %} {{ article.current_revision.title }}
        </a>
      </li>
    </ul>
  </div>
</div>
<div style="clear: both"></div>
</div>
{% endif %}

wiki/templates/wiki/includes/editor.html
{% load wiki_tags i18n sekizai_tags %}
{% include "wiki/includes/editormedia.html" %}

{% wiki_form form %}
{% addtoblock "js" %}
<script language="javascript">
  $(document).ready(function() {
    $("#id_revision").val('{{ article.current_revision.id }}');
  });
</script>
{% endaddtoblock %}

wiki/templates/wiki/includes/editor_sidebar.html
{% load i18n sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript">
  $(document).ready( function() {
    $('.sidebar-form').each(function () {
      $(this).submit( function() {
        this.unsaved_article_title.value = $('#id_title').val();
        this.unsaved_article_content.value = $('#id_content').val();
      });
    });
  });
</script>
{% endaddtoblock %}

<div class="panel-group" id="accordion">

{% for plugin, plugin_form in sidebar %}



  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_{{ plugin.slug }}">
          {{ plugin.sidebar.headline }} <span class="icon {{ plugin.sidebar.icon_class }} pull-right"></span>
        </a>
      </h4>
    </div>
    <div id="collapse_{{ plugin.slug }}" class="panel-collapse collapse{% if plugin_form.errors %} in{% endif %}">
      <div class="panel-body">
        {% if plugin.sidebar.template %}
          {% with plugin_form as form and plugin as plugin %}
            <form method="POST" class="form-horizontal sidebar-form" action="?f={{ plugin_form.form_id }}" enctype="multipart/form-data">
              {% csrf_token %}
              {% include plugin.sidebar.template %}
            </form>
          {% endwith %}
        {% endif %}
      </div>
    </div>
  </div>







{##}
{##}
{##}
{#  <div class="accordion-group">#}
{#    #}
{#    <div class="accordion-heading">#}
{#      <a class="accordion-toggle" href="#collapse_{{ plugin.slug }}" data-toggle="collapse">#}
{#        <h3>{{ plugin.sidebar.headline }} <span class="icon {{ plugin.sidebar.icon_class }}"></span></h3>#}
{#      </a>#}
{#    </div>#}
{#    #}
{#    <div id="collapse_{{ plugin.slug }}" class="accordion-body collapse{% if plugin_form.errors %} in{% endif %}">#}
{#      <div class="accordion-inner form-vertical">#}
{#        {% if plugin.sidebar.template %}#}
{#          {% with plugin_form as form and plugin as plugin %}#}
{#            <form method="POST" class="form-horizontal sidebar-form" action="?f={{ plugin_form.form_id }}" enctype="multipart/form-data">#}
{#              {% csrf_token %}#}
{#              {% include plugin.sidebar.template %}#}
{#            </form>#}
{#          {% endwith %}#}
{#        {% endif %}#}
{#      </div>#}
{#    </div>#}
{#  #}
{#  </div>#}
{% endfor %}
</div>

wiki/templates/wiki/includes/editormedia.html
{% load sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/editor.js"></script>
{% for js in editor.Media.js %}
<script type="text/javascript" src="{{ STATIC_URL }}{{ js }}"></script>
{% endfor %}
{% endaddtoblock %}

{% addtoblock "css" %}
{% for media, srcs in editor.Media.css.items %}
  {% for src in srcs %}
    <link rel="stylesheet" media="{{ media }}" href="{{ STATIC_URL }}{{ src }}" />
  {% endfor %}
{% endfor %}
{% endaddtoblock %}

wiki/templates/wiki/includes/form.html
{% csrf_token %}{% load sekizai_tags %}

{% include "wiki/includes/formerrors.html" %}

{% addtoblock "js" %}
{{ form.media.js }}
{% endaddtoblock %}

{% addtoblock "css" %}
{{ form.media.css }}
{% endaddtoblock %}

{% for field in form %}

  {% include "wiki/includes/formfield.html" %}

{% endfor %}

wiki/templates/wiki/includes/formerrors.html
{% if form.non_field_errors %}
  {% if form_error_title %}<h4 class="alert-heading">{{ form_error_title }}</h4>{% endif %}
  {% for error_message in form.non_field_errors %}
    <div class="alert alert-block alert-error">
      {{ error_message }}
    </div>    
  {% endfor %}
{% endif %}

wiki/templates/wiki/includes/formfield.html
{% if field.is_hidden %}
  {{ field }}
{% else %}

<div id="div_{{ field.auto_id }}" class="form-group{% if field.errors %} has-error{% endif %}">
  <div class="wiki-label col-lg-2">
  {% if field.label %}
    <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
    {{ field.label|safe }}
    </label>
  {% endif %}
  </div>
  <div class="wiki-control col-lg-10">
    {{ field }} {% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
    {% if field.errors %}
      {% for error in field.errors %}
        <div id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></div>
      {% endfor %}
    {% endif %}
    {% if field.help_text %}
      <p id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</p>
    {% endif %}
  </div>
</div>
{% endif %}

wiki/templates/wiki/includes/modals.html
{% load sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/jqueryui/jquery-ui-1.10.0.custom.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $(".modal-content").on("resizestart", function(event, ui) {
    $(ui.element).find(".modal-body, iframe").each(function() {
      elem = $(this);
      elem.data("resizeoriginalheight", elem.height());
    });
  });

  $(".modal-content").on("resize", function(event, ui) {
      ui.element.parents('.modal-dialog').css("margin-left", -ui.size.width/2);
      ui.element.parents('.modal-dialog').css("margin-top", -ui.size.height/2);
      ui.element.parents('.modal-dialog').css("top", "50%");
      ui.element.parents('.modal-dialog').css("left", "50%");

      $(ui.element).find(".modal-body,iframe").each(function() {
        elem = $(this);
        $(this).css("min-height", elem.data("resizeoriginalheight") + ui.size.height - ui.originalSize.height);
      });
  });

  $(".modal-content").resizable();
});
</script>
{% endaddtoblock %}
{% addtoblock "css" %}
<link rel="stylesheet" href="{{ STATIC_URL }}wiki/js/jqueryui/jquery-ui-1.10.0.custom.min.css" type="text/css" />
{% endaddtoblock %}

wiki/templates/wiki/includes/pagination.html
{% load i18n %}
{% if is_paginated %}
<div class="pagination">
  <ul>
    {% for pc in paginator.page_range %}
    <li class="{% if pc == page_obj.number %} active{% endif %}"><a href="?page={{ pc }}{% if appended_key %}&{{ appended_key }}={{ appended_value }}{% endif %}">{{ pc }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endif %}

wiki/templates/wiki/includes/render.html
{% load wiki_tags i18n cache sekizai_tags static %}

{% addtoblock "js" %}        
  <script type="text/javascript" src="{% static "wiki/js/article.js"%}"></script>
{% endaddtoblock %}

<div class="wiki-article">
  {% if not preview %}
    {% if article.current_revision %}
      {{ article.get_cached_content }}
    {% endif %}
  {% else %}
    {{ content|default:"" }}
  {% endif %}
</div>

{% for plugin in plugins %}
  {% if plugin.RenderMedia.css %}
    {% addtoblock "css" %}
      {% for media, url in plugin.RenderMedia.css.items %}
        <link rel="stylesheet" href="{% static url %}" />
      {% endfor %}
    {% endaddtoblock %}
  {% endif %}
  {% if plugin.RenderMedia.js %}
    {% addtoblock "js" %}        
      {% for url in plugin.RenderMedia.js %}
        <script type="text/javascript" src="{% static url %}"></script>
      {% endfor %}
    {% endaddtoblock %}
  {% endif %}
{% endfor %}

wiki/templates/wiki/includes/revision_info.html
{% comment %}

  This reusable code is shared between different templates and different inheritors of
  BaseRevision.

{% endcomment %}


{% load wiki_tags i18n %}
{% if not hidedate %}{{ revision.created }}{% endif %} {% if not hidenumber %}(#{{ revision.revision_number }}) {% trans "by" %}{% endif %} {% if revision.user %}{{ revision.user }}{% else %}{% if article|can_moderate:user %}{{ revision.ip_address|default:"anonymous (IP not logged)" }}{% else %}{% trans "anonymous (IP logged)" %}{% endif %}{% endif %}
{% if revision == current_revision %}
  <strong>*</strong>
{% endif %}
{% if revision.deleted %}
<span class="badge badge-important">{% trans "deleted" %}</span>
{% endif %}
{% if revision.previous_revision.deleted and not revision.deleted %}
<span class="badge badge-success">{% trans "restored" %}</span>
{% endif %}
{% if revision.locked %}
<span class="badge">{% trans "locked" %}</span>
{% endif %}
{% if revision.previous_revision.locked and not revision.locked %}
<span class="badge">{% trans "unlocked" %}</span>
{% endif %}

wiki/templates/wiki/includes/searchresult.html
{% load wiki_tags i18n humanize %}
{% load url from future %}

<tr>
  <td>
    {% for urlpath in article.urlpath_set.all %}
      <a href="{% url 'wiki:get' path=urlpath.path %}">{{ article.current_revision.title }}<br /><small class="muted">/{{ urlpath.path }}</small></a>
    {% empty %}
      <a href="{% url 'wiki:get' article_id=article.id %}">{{ article.current_revision.title }}</a>
    {% endfor %}
    {% if article.current_revision.deleted %}
      <span class="icon-trash"></span>
    {% endif %}
    {% if article.current_revision.locked %}
      <span class="icon-lock"></span>
    {% endif %}
    <p class="muted"><small>{{ article.current_revision.content|get_content_snippet:search_query }}</small></p>
  </td>
  <td style="white-space: nowrap">
    {{ article.current_revision.created|naturaltime }}
  </td>
</tr>